### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by huangkeju** [vicariousinc/science_rcn#13]
The program works with the provied MNIST data, but failed when trained with other data, printing the following message:
------------------------------------------------------------------------------------------------------------------
INFO:__main__:Training on 20 images...
Traceback (most recent call last):
  File "science_rcn/run.py", line 230, in <module>
    parallel=options.parallel)
  File "science_rcn/run.py", line 83, in run_experiment
    train_results = pool.map_async(train_partial, [d[0] for d in train_data]).get(9999999)
  File "D:\Anaconda\envs\py27\lib\multiprocessing\pool.py", line 572, in get
    raise self._value
IndexError: too many indices for array
-------------------------------------------------------------------------------------------------------------------
Does anyone has any idea how to solve this?

**Comment by sunhao123456789** [comment]
too many indices for array 请问这个问题您解决了吗？，可以指点下吗?
