### ISSUE TITLE
How to train using  Yahoo or reCaptcha?

### ISSUE THREAD

**Issue by yeguixin** [vicariousinc/science_rcn#5]
I tried to using the program to train using Yahoo's data provided in your blog, but failed to print the following error message:
------------------------------------------------------------------------------
INFO:__main__:Training on 124 images...
INFO:__main__:Testing on 0 images...
Traceback (most recent call last):
  File "science_rcn/run.py", line 230, in <module>
    parallel=options.parallel)
  File "science_rcn/run.py", line 95, in run_experiment
    print "Total test accuracy = {}".format(float(correct) / len(test_results))
ZeroDivisionError: float division by zero
---------------------------------------------------------------------------------
We used the following commond:
python science_rcn/run.py --train_size 20 --test_size 20 --parallel

Thanks

**Comment by tbraga14** [comment]
Hi Yeguixin, 

- The problem occurs at:

> INFO:main:Testing on 0 images...

This means run.py cannot access testing samples. I can reproduce your error by removing folders 0/1/2.. from /testing of the provided MNIST dataset. Therefore, it may be the folder structure, as line 133 `def _load_data`  assumes...

>         training/
>             0/
>             1/
>             2/
>             ...
>         testing/
>             0/
>             ...

.. inside data/MNIST folder.

This git was made to work with MNIST at first so you have to modify the file(s) yourself if you want to run other datasets. A simple command won't do it in this case.

**Comment by yeguixin** [comment]
I know, you mean you only published the code to recognize MNIST? But I want to konw how to train and test the Yahoo or reCaptcha using the dataset you provided in your paper. Thanks.

**Comment by tbraga14** [comment]
Hi Yeguixin,

Sorry, but, just to clarify, it wasn't I who published the code/research. I just meant to help by what I could see in the code directly (run.py, line 2):

`Reference implementation of a two-level RCN model for MNIST classification experiments.`

I'm afraid I can't provide a better answer than that so you could wait for an official reply from the devs. Thanks.

**Comment by yeguixin** [comment]
I see. Thanks

**Comment by Chong-Jiao** [comment]
@yeguixin Have you successfully applied it to the traning and testing in the reCaptcha dataset? if so, could you share you codes with me?

**Comment by Chong-Jiao** [comment]
@yeguixin Have you successfully applied it to the traning and testing in the reCaptcha dataset? if so, could you share you codes with me?

**Comment by liwanyue123** [comment]
anyone succeed ？

**Comment by yashy23** [comment]
did anyone got it ??
